name: CI Containers
on:
  workflow_dispatch:

jobs:
  base_image_ubuntu2004:
    name: Base Ubuntu 20.04 Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ubuntu2004_base:${{ github.sha }}
            ghcr.io/${{ github.repository }}/ubuntu2004_base:latest
          context: ${{ github.workspace }}/devops
          file: ${{ github.workspace }}/devops/containers/ubuntu2004_base.Dockerfile
  drivers_image_ubuntu2004:
    needs: base_image_ubuntu2004
    name: Intel Drivers Ubuntu 20.04 Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            organization=${{ github.repository_owner }}
          tags: |
            ghcr.io/${{ github.repository }}/ubuntu2004_intel_drivers:${{ github.sha }}
            ghcr.io/${{ github.repository }}/ubuntu2004_intel_drivers:latest
          context: ${{ github.workspace }}/devops
          file: ${{ github.workspace }}/devops/containers/ubuntu2004_intel_drivers.Dockerfile

