name: Linux Post Commit Checks

on:
  push:
    branches:
      - sycl
  pull_request:
    branches:
      - sycl
    paths:
      - .github/workflows/sycl_post_commit.yml

jobs:
  linux_default:
    name: Linux Default
    if: github.repository == 'intel/llvm'
    uses: intel/llvm/.github/workflows/sycl_linux_build_and_test.yml@sycl
    with:
      build_runs_on: sycl-precommit-linux
      build_cache_root: "/__w/"
      build_cache_size: "8G"
      build_artifact_suffix: default
  linux_no_assert:
    name: Linux (no assert)
    if: github.repository == 'intel/llvm'
    uses: intel/llvm/.github/workflows/sycl_linux_build_and_test.yml@sycl
    with:
      build_cache_root: "/__w/llvm"
      build_github_cache: true
      build_cache_suffix: gcc_no_assertions
      build_artifact_suffix: gcc_no_assertions
      build_configure_extra_args: --no-assertions
  linux_clang_shared_libs:
    name: Linux (clang + shared libs)
    if: github.repository == 'intel/llvm'
    uses: intel/llvm/.github/workflows/sycl_linux_build_and_test.yml@sycl
    with:
      build_image: "ghcr.io/intel/llvm/sycl_ubuntu2004_nightly:no-drivers"
      build_cache_root: "/__w/llvm"
      build_github_cache: true
      build_cache_suffix: clang_shared_libs
      build_artifact_suffix: clang_shared_libs
      build_configure_extra_args: --shared-libs
