name: Linux Post Commit Checks

on:
  push:
    branches:
      - sycl
  pull_request:
    paths:
    - '.github/workflows/sycl_post_commit.yml'

jobs:
  linux_default:
    name: Linux Default
    uses: intel/llvm/.github/workflows/sycl_linux_build_and_test.yml@sycl
    with:
      build_runs_on: build
      build_cache_root: "/__w/llvm"
      build_github_cache: true
      build_artifact_suffix: default
  linux_no_assert:
    name: Linux (no assert)
    uses: intel/llvm/.github/workflows/sycl_linux_build_and_test.yml@sycl
    with:
      build_runs_on: build
      build_cache_root: "/__w/llvm"
      build_github_cache: true
      build_cache_suffix: gcc_no_assertions
      build_artifact_suffix: gcc_no_assertions
      build_configure_extra_args: --no-assertions
  linux_self_prod:
    name: Linux (Self build + shared libraries)
    uses: intel/llvm/.github/workflows/sycl_linux_build_and_test.yml@sycl
    with:
      build_runs_on: build
      build_cache_root: "/__w/llvm"
      build_github_cache: true
      build_cache_suffix: sprod_shared
      build_artifact_suffix: sprod_shared
      build_configure_extra_args: --shared-libs
      build_image: "ghcr.io/intel/llvm/sycl_ubuntu2004_nightly:no-drivers"
      cc: clang
      cxx: clang++
