name: SYCL

on:
  pull_request:
    branches:
    - sycl

jobs:
  test:
    runs-on: X64
    container:
      image: ghcr.io/intel/llvm/sycl_ubuntu2004_nightly:no-drivers
    steps:
    - run: apt update && apt install -yqq gdb
    - run: sycl-ls --verbose
