name: SYCL

on:
  pull_request:
    branches:
    - sycl

jobs:
  test:
    runs-on: X64
    container:
      image: ghcr.io/intel/llvm/sycl_ubuntu2004_nightly:no-drivers
    steps:
    - run: apt update && apt install -yqq gdb
    - run: gdb -q --batch \
             -ex 'handle SIGHUP nostop pass' \
               -ex 'handle SIGQUIT nostop pass' \
               -ex 'handle SIGPIPE nostop pass' \
               -ex 'handle SIGALRM nostop pass' \
               -ex 'handle SIGTERM nostop pass' \
               -ex 'handle SIGUSR1 nostop pass' \
               -ex 'handle SIGUSR2 nostop pass' \
               -ex 'handle SIGCHLD nostop pass' \
               -ex 'set print thread-events off' \
               -ex 'run' \
               -ex 'thread apply all bt' \
             --args /opt/sycl/bin/sycl-ls --verbose
